// design-doc.mjs — Superpowers-style brainstorming design document
//
// Produces a structured design document before implementation.
// Saves to DESIGNS/ directory for traceability.
// Aligns with: brainstorming first, spec before code.

import { mkdirSync, writeFileSync, existsSync } from 'node:fs';
import { resolve, join } from 'node:path';
import { cwd } from 'node:process';

export default {
  name: 'smart_design_doc',
  category: 'standard',
  description: `產出結構化設計文件（Superpowers brainstorming）。
開發任何新功能前先產出此文件，確保 spec 與實作一致。

欄位：Goal / Context / Approach / Risks / Test Plan

會自動儲存到 DESIGNS/ 目錄。`,
  inputSchema: {
    type: 'object',
    properties: {
      goal: { type: 'string', description: 'Goal in one sentence (required)' },
      context: { type: 'string', description: 'Background, constraints, existing architecture' },
      approach: { type: 'string', description: 'Implementation approach and reasoning' },
      risks: { type: 'string', description: 'Known risks, edge cases, failure modes' },
      testPlan: { type: 'string', description: 'How to verify correctness' },
      acceptanceCriteria: { type: 'string', description: 'List of acceptance criteria' },
      outputDir: { type: 'string', description: 'Output directory (default: DESIGNS/)' },
      save: { type: 'boolean', description: 'Save to file (default: true)' }
    },
    required: ['goal']
  },
  responsePolicy: { maxLevel: 0 },

  handler: async (args) => {
    const goal = args.goal;
    const slug = goal
      .toLowerCase()
      .replace(/[^a-z0-9]+/g, '-')
      .replace(/^-|-$/g, '')
      .slice(0, 60);
    const timestamp = new Date().toISOString().slice(0, 10);
    const filename = `${timestamp}-${slug}.md`;

    const doc = [
      '---',
      `title: ${goal}`,
      `date: ${timestamp}`,
      `status: draft`,
      `type: design`,
      '---',
      '',
      `# ${goal}`,
      '',
      '## Goal',
      '',
      goal,
      '',
      '## Context',
      '',
      args.context || 'TBD — document background and constraints',
      '',
      '## Approach',
      '',
      args.approach || 'TBD — describe the implementation approach',
      '',
      '## Acceptance Criteria',
      '',
      args.acceptanceCriteria
        ? args.acceptanceCriteria.split('\n').map(l => `- [ ] ${l}`).join('\n')
        : '- [ ] TBD — define acceptance criteria',
      '',
      '## Risks & Edge Cases',
      '',
      args.risks || 'TBD — identify known risks',
      '',
      '## Test Plan',
      '',
      args.testPlan || 'TBD — describe how to verify',
      '',
      '---',
      '',
      '_Generated by smart_design_doc — modify as implementation progresses._',
    ].join('\n');

    let outputPath = '';
    if (args.save !== false) {
      const dir = resolve(args.outputDir || join(cwd(), 'DESIGNS'));
      if (!existsSync(dir)) mkdirSync(dir, { recursive: true });
      outputPath = join(dir, filename);
      writeFileSync(outputPath, doc, 'utf-8');
    }

    return JSON.stringify({
      ok: true,
      saved: !!outputPath,
      path: outputPath || '(dry-run, not saved)',
      filename,
      document: doc,
      instruction: `設計文件已${outputPath ? '儲存至 ' + outputPath : '產生（未儲存）'}。
在實作前先與使用者確認 acceptance criteria，然後開始實作。`
    }, null, 2);
  }
};
