#!/usr/bin/env bash
# robot_quarantine.sh — 機器人專區隔離守衛
# 功能：確保機器人專區（10-感知層/、85-機器人索引/）不被人類直接進入
# 使用：bash robot_quarantine.sh {scan|fence|check|status}

set -euo pipefail

VAULT="${OBSIDIAN_VAULT:-$HOME/.obsidian-wiki}"
LOG_DIR="$HOME/.config/opencode/logs"
QUARANTINE_LOG="$LOG_DIR/quarantine.jsonl"

# 機器人專區目錄
ROBOT_ZONES=(
  "10-感知層"
  "85-機器人索引"
)

mkdir -p "$LOG_DIR"

# 取得目前時間戳
timestamp() {
  date '+%Y-%m-%d %H:%M:%S'
}

# 記錄事件
log_event() {
  local event_type="$1"
  local target="$2"
  local status="$3"
  echo "{\"ts\":\"$(timestamp)\",\"type\":\"$event_type\",\"target\":\"$target\",\"status\":\"$status\"}" >> "$QUARANTINE_LOG"
}

# 檢查目錄是否存在
check_zone_exists() {
  local zone="$1"
  local zone_path="$VAULT/$zone"
  if [[ -d "$zone_path" ]]; then
    return 0
  else
    return 1
  fi
}

# 檢查目錄中是否有非機器人標記的檔案
check_human_contamination() {
  local zone="$1"
  local zone_path="$VAULT/$zone"
  local contaminated=0

  if [[ ! -d "$zone_path" ]]; then
    return 0
  fi

  # 掃描所有 .md 檔案
  while IFS= read -r -d '' file; do
    # 檢查是否有 robot-generated 或 llm-generated 標記
    if ! grep -qE "(robot-generated|llm-generated|Generated by|機器人生成)" "$file" 2>/dev/null; then
      echo "  ⚠️ 可能的人類檔案：${file#$VAULT/}"
      contaminated=1
    fi
  done < <(find "$zone_path" -name "*.md" -print0 2>/dev/null)

  return $contaminated
}

# 命令：scan — 掃描機器人專區
cmd_scan() {
  echo "🔍 掃描機器人專區"
  echo "================"

  for zone in "${ROBOT_ZONES[@]}"; do
    echo ""
    echo "📁 $zone/"

    if check_zone_exists "$zone"; then
      local zone_path="$VAULT/$zone"
      local file_count
      file_count=$(find "$zone_path" -name "*.md" | wc -l | tr -d ' ')
      echo "  ✅ 目錄存在（$file_count 個頁面）"

      # 檢查污染
      if check_human_contamination "$zone"; then
        echo "  ⚠️ 發現可能的人類檔案"
        log_event "contamination_found" "$zone" "warning"
      else
        echo "  ✅ 無人類污染"
        log_event "scan_clean" "$zone" "ok"
      fi
    else
      echo "  ℹ️ 目錄不存在（將在 fence 時建立）"
    fi
  done

  echo ""
  echo "📊 掃描完成"
}

# 命令：fence — 建立隔離圍欄
cmd_fence() {
  echo "🏗️ 建立隔離圍欄"
  echo "================"

  for zone in "${ROBOT_ZONES[@]}"; do
    local zone_path="$VAULT/$zone"

    # 建立目錄
    mkdir -p "$zone_path"

    # 建立隔離說明頁面
    local quarantine_page="$zone_path/_隔離說明.md"
    if [[ ! -f "$quarantine_page" ]]; then
      cat > "$quarantine_page" <<'EOF'
# 🚧 機器人專區隔離說明

> ⚠️ 此目錄為機器人專用區域，人類請勿直接進入

## 規則
1. 此目錄中的檔案由機器人自動產生
2. 人類不應直接編輯此目錄中的檔案
3. 所有變更需經進出控制系統審核
4. 機器人進入需取得人類同意

## 檔案格式
- 所有頁面應包含 `robot-generated` 或 `llm-generated` 標記
- 頁面應包含產生時間和機器人識別碼

## 相關文件
- [[/_隔離說明|隔離說明]]
- [[/00-入口/機器人首頁|機器人首頁]]
EOF
      echo "  ✅ 建立隔離說明：$quarantine_page"
    fi

    # 建立 .gitignore（如果使用 git）
    local gitignore="$zone_path/.gitignore"
    if [[ ! -f "$gitignore" ]]; then
      cat > "$gitignore" <<'EOF'
# 機器人專區 — 忽略臨時檔案
*.tmp
*.bak
.DS_Store
EOF
      echo "  ✅ 建立 .gitignore"
    fi

    log_event "fence_created" "$zone" "ok"
    echo "  ✅ 隔離圍欄已建立：$zone"
  done

  echo ""
  echo "✅ 隔離圍欄建立完成"
}

# 命令：check — 檢查特定檔案是否在隔離區
cmd_check() {
  local target="$1"
  local in_quarantine=0

  for zone in "${ROBOT_ZONES[@]}"; do
    if [[ "$target" == "$zone"* ]]; then
      in_quarantine=1
      echo "🔒 $target 位於機器人專區：$zone/"
      break
    fi
  done

  if [[ $in_quarantine -eq 0 ]]; then
    echo "✅ $target 不在機器人專區"
  fi

  return $in_quarantine
}

# 命令：status — 查看隔離狀態
cmd_status() {
  echo "📊 機器人專區隔離狀態"
  echo "===================="

  for zone in "${ROBOT_ZONES[@]}"; do
    local zone_path="$VAULT/$zone"
    echo ""
    echo "📁 $zone/"

    if check_zone_exists "$zone"; then
      local file_count
      file_count=$(find "$zone_path" -name "*.md" | wc -l | tr -d ' ')
      echo "  📄 頁面數：$file_count"
      echo "  🔒 狀態：已隔離"
    else
      echo "  ℹ️ 目錄不存在"
      echo "  🔒 狀態：未建立"
    fi
  done

  echo ""
  if [[ -f "$QUARANTINE_LOG" ]]; then
    echo "📋 最近事件："
    tail -5 "$QUARANTINE_LOG" | while read -r line; do
      local ts event target status
      ts=$(echo "$line" | grep -o '"ts": "[^"]*"' | cut -d'"' -f4)
      event=$(echo "$line" | grep -o '"type": "[^"]*"' | cut -d'"' -f4)
      target=$(echo "$line" | grep -o '"target": "[^"]*"' | cut -d'"' -f4)
      echo "  [$ts] $event → $target"
    done
  fi
}

# 主程式
main() {
  local cmd="${1:-help}"
  shift || true

  case "$cmd" in
    scan)
      cmd_scan
      ;;
    fence)
      cmd_fence
      ;;
    check)
      [[ $# -ge 1 ]] || { echo "用法：$0 check <path>"; exit 1; }
      cmd_check "$1"
      ;;
    status)
      cmd_status
      ;;
    *)
      echo "用法：$0 {scan|fence|check|status}"
      echo ""
      echo "命令："
      echo "  scan              — 掃描機器人專區"
      echo "  fence             — 建立隔離圍欄"
      echo "  check <path>      — 檢查路徑是否在隔離區"
      echo "  status            — 查看隔離狀態"
      exit 1
      ;;
  esac
}

main "$@"
