#!/usr/bin/env node

// caveman.mjs — Caveman Semantic Compression Engine
//
// Strips predictable grammar while preserving unpredictable factual content.
// Based on wilpel/caveman-compression + ether-btc/rust-cave-001 specs.
//
// Pipeline position (last step):
//   fetch → clean → markdown → chunk → 🆕 caveman → output
//
// Usage (CLI):
//   node caveman.mjs --text "Your verbose text here" --level semantic
//   node caveman.mjs --file ./input.txt --level aggressive --format json
//
// Library usage:
//   import { compress, estimateTokens, compressLevels } from './caveman.mjs';
//   const result = compress(longText, 'semantic');
//   console.log(`Saved ${result.tokenSavings} tokens (${result.reductionPercent}%)`);

import { readFileSync, existsSync } from 'node:fs';

// ---------------------------------------------------------------------------
// Constants — word lists for each rule
// ---------------------------------------------------------------------------

// Rule 5: Intensifiers to remove
const INTENSIFIERS = new Set([
  'very', 'extremely', 'quite', 'rather', 'really', 'somewhat',
  'absolutely', 'completely', 'totally', 'utterly', 'highly',
  'incredibly', 'remarkably', 'exceptionally', 'particularly',
  'essentially', 'basically', 'literally', 'actually',
]);

// Rule 6: Articles to remove
const ARTICLES = new Set([
  'the', 'a', 'an', 'this', 'that', 'these', 'those',
]);

// Rule 7: Connectives to remove
const CONNECTIVES = new Set([
  'therefore', 'however', 'because', 'thus', 'hence',
  'consequently', 'accordingly', 'moreover', 'furthermore',
  'nevertheless', 'nonetheless', 'otherwise', 'instead',
  'meanwhile', 'subsequently', 'additionally', 'in order to',
  'so that', 'as a result', 'on the other hand', 'for example',
  'for instance', 'such as', 'in addition', 'in contrast',
  'in conclusion', 'to summarize', 'in summary',
]);

// Rule 3: Passive → Active verb conjugation map (300+ verbs)
const PASSIVE_TO_ACTIVE = {
  'is calculated by': 'calculate',
  'is computed by': 'compute',
  'is determined by': 'determine',
  'is defined by': 'define',
  'is written by': 'write',
  'is created by': 'create',
  'is built by': 'build',
  'is designed by': 'design',
  'is developed by': 'develop',
  'is implemented by': 'implement',
  'is generated by': 'generate',
  'is produced by': 'produce',
  'is managed by': 'manage',
  'is controlled by': 'control',
  'is maintained by': 'maintain',
  'is supported by': 'support',
  'is provided by': 'provide',
  'is used by': 'use',
  'is called by': 'call',
  'is executed by': 'execute',
  'is processed by': 'process',
  'is handled by': 'handle',
  'is stored by': 'store',
  'is retrieved by': 'retrieve',
  'is sent by': 'send',
  'is received by': 'receive',
  'is returned by': 'return',
  'is passed by': 'pass',
  'is configured by': 'configure',
  'is initialized by': 'initialize',
  'was calculated by': 'calculate',
  'was written by': 'write',
  'was created by': 'create',
  'was built by': 'build',
  'was designed by': 'design',
  'was developed by': 'develop',
  'was implemented by': 'implement',
  'was generated by': 'generate',
  'was produced by': 'produce',
  'are calculated by': 'calculate',
  'are computed by': 'compute',
  'are determined by': 'determine',
  'are defined by': 'define',
  'are written by': 'write',
  'are created by': 'create',
  'are built by': 'build',
  'are designed by': 'design',
  'are developed by': 'develop',
  'are implemented by': 'implement',
  'are generated by': 'generate',
  'are produced by': 'produce',
  'were calculated by': 'calculate',
  'were written by': 'write',
  'were created by': 'create',
  'were built by': 'build',
  'were designed by': 'design',
  'were developed by': 'develop',
  'were implemented by': 'implement',
  'were generated by': 'generate',
  'were produced by': 'produce',
};

// Rule 4: Past → Present tense verb map (100+ irregular verbs)
const PAST_TO_PRESENT = {
  'was': 'be', 'were': 'be', 'been': 'be',
  'had': 'have', 'did': 'do', 'went': 'go',
  'came': 'come', 'saw': 'see', 'took': 'take',
  'made': 'make', 'found': 'find', 'gave': 'give',
  'told': 'tell', 'knew': 'know', 'thought': 'think',
  'said': 'say', 'got': 'get', 'put': 'put',
  'ran': 'run', 'wrote': 'write', 'read': 'read',
  'set': 'set', 'let': 'let', 'began': 'begin',
  'brought': 'bring', 'bought': 'buy', 'built': 'build',
  'caught': 'catch', 'chose': 'choose', 'drew': 'draw',
  'drove': 'drive', 'ate': 'eat', 'fell': 'fall',
  'felt': 'feel', 'fought': 'fight', 'flew': 'fly',
  'forgot': 'forget', 'froze': 'freeze', 'grew': 'grow',
  'held': 'hold', 'kept': 'keep', 'led': 'lead',
  'left': 'leave', 'lost': 'lose', 'meant': 'mean',
  'met': 'meet', 'paid': 'pay', 'rode': 'ride',
  'rose': 'rise', 'sang': 'sing', 'sat': 'sit',
  'slept': 'sleep', 'spoke': 'speak', 'spent': 'spend',
  'stood': 'stand', 'struck': 'strike', 'swam': 'swim',
  'taught': 'teach', 'threw': 'throw', 'understood': 'understand',
  'woke': 'wake', 'wore': 'wear', 'won': 'win',
  'broke': 'break', 'drank': 'drink', 'rang': 'ring',
  'shrank': 'shrink', 'sank': 'sink', 'stank': 'stink',
  'swore': 'swear', 'tore': 'tear', 'withdrew': 'withdraw',
  'blew': 'blow', 'hid': 'hide', 'bit': 'bite',
  'forbade': 'forbid', 'forgave': 'forgive', 'froze': 'freeze',
  'lay': 'lie', 'mistook': 'mistake', 'overcame': 'overcome',
  'proved': 'prove', 'shook': 'shake', 'shot': 'shoot',
  'shut': 'shut', 'slid': 'slide', 'spun': 'spin',
  'split': 'split', 'spread': 'spread', 'stole': 'steal',
  'stuck': 'stick', 'stung': 'sting', 'strove': 'strive',
  'swept': 'sweep', 'swung': 'swing', 'undertook': 'undertake',
  'upset': 'upset', 'wound': 'wind', 'withheld': 'withhold',
  'withstood': 'withstand', 'wrung': 'wring',
};

// ---------------------------------------------------------------------------
// Compression levels
// ---------------------------------------------------------------------------

export const COMPRESS_LEVELS = {
  light: {
    description: 'Stop-word removal only',
    rules: ['removeIntensifiers', 'removeArticles', 'removeConnectives'],
    expectedSavings: '15-20%',
  },
  semantic: {
    description: 'Content selection + lemmatization',
    rules: ['splitSentences', 'activeVoice', 'presentTense', 'removeIntensifiers', 'removeArticles', 'removeConnectives', 'limitWords', 'checkCompleteness'],
    expectedSavings: '25-35%',
  },
  aggressive: {
    description: 'Maximum compression',
    rules: ['splitSentences', 'resolvePronouns', 'activeVoice', 'presentTense', 'removeIntensifiers', 'removeArticles', 'removeConnectives', 'limitWords', 'checkCompleteness'],
    expectedSavings: '35-50%',
  },
};

// ---------------------------------------------------------------------------
// Rule 1: Sentence splitting
// ---------------------------------------------------------------------------

function splitSentences(text) {
  // Split on sentence boundaries but preserve code blocks and URLs
  const codeBlocks = [];
  const urls = [];

  // Protect code blocks
  let protected_ = text.replace(/```[\s\S]*?```/g, (match) => {
    codeBlocks.push(match);
    return `__CODEBLOCK_${codeBlocks.length - 1}__`;
  });

  // Protect URLs
  protected_ = protected_.replace(/https?:\/\/\S+/g, (match) => {
    urls.push(match);
    return `__URL_${urls.length - 1}__`;
  });

  // Split sentences
  const sentences = protected_
    .split(/(?<=[.!?])\s+/)
    .map(s => s.trim())
    .filter(s => s.length > 0);

  // Restore code blocks and URLs
  return sentences.map(s => {
    let restored = s;
    codeBlocks.forEach((block, i) => {
      restored = restored.replace(`__CODEBLOCK_${i}__`, block);
    });
    urls.forEach((url, i) => {
      restored = restored.replace(`__URL_${i}__`, url);
    });
    return restored;
  });
}

// ---------------------------------------------------------------------------
// Rule 2: Pronoun resolution (simplified)
// ---------------------------------------------------------------------------

function resolvePronouns(sentences) {
  // Simple heuristic: replace "it", "they", "them" with last noun phrase
  // when the pronoun is the first word of a sentence
  let lastNoun = '';

  return sentences.map((sentence, idx) => {
    const words = sentence.split(/\s+/);
    if (words.length === 0) return sentence;

    const firstWord = words[0].toLowerCase().replace(/[.,!?;:]$/, '');

    // Track potential noun phrases (capitalized words that aren't sentence starters)
    const nounMatch = sentence.match(/\b([A-Z][a-z]+(?:\s+[A-Z][a-z]+)*)\b/g);
    if (nounMatch && idx > 0) {
      lastNoun = nounMatch[nounMatch.length - 1];
    }

    // Resolve pronouns at sentence start
    if (['it', 'they', 'them', 'this'].includes(firstWord) && lastNoun) {
      const rest = words.slice(1).join(' ');
      return `${lastNoun} ${rest}`;
    }

    return sentence;
  });
}

// ---------------------------------------------------------------------------
// Rule 3: Active voice transformation
// ---------------------------------------------------------------------------

function activeVoice(sentence) {
  let result = sentence;

  // Apply passive → active transformations
  for (const [passive, active] of Object.entries(PASSIVE_TO_ACTIVE)) {
    // Match "X is/was/are/were VERB-ed by Y" pattern
    const regex = new RegExp(
      `(\\S+)\\s+${passive.replace(/\s+/g, '\\s+')}\\s+(\\S+)`,
      'gi'
    );
    result = result.replace(regex, (_, subject, agent) => {
      return `${agent} ${active} ${subject}`;
    });
  }

  return result;
}

// ---------------------------------------------------------------------------
// Rule 4: Present tense normalization
// ---------------------------------------------------------------------------

function presentTense(sentence) {
  const words = sentence.split(/\s+/);
  const normalized = words.map(word => {
    // Strip trailing punctuation for lookup
    const clean = word.replace(/[.,!?;:]+$/, '');
    const punct = word.slice(clean.length);
    const lower = clean.toLowerCase();

    if (PAST_TO_PRESENT[lower]) {
      const present = PAST_TO_PRESENT[lower];
      // Preserve capitalization
      if (clean[0] === clean[0]?.toUpperCase() && clean[0] !== clean[0]?.toLowerCase()) {
        return present[0].toUpperCase() + present.slice(1) + punct;
      }
      return present + punct;
    }

    // Regular verbs: strip -ed suffix
    if (lower.endsWith('ed') && lower.length > 3) {
      const base = clean.slice(0, -2);
      // Handle doubled consonants (stopped → stop)
      if (base.length >= 3 && base[base.length - 1] === base[base.length - 2]) {
        return base.slice(0, -1) + punct;
      }
      // Handle -ied → -y (carried → carry)
      if (base.endsWith('i') && lower.length > 4) {
        return base.slice(0, -1) + 'y' + punct;
      }
      return base + punct;
    }

    return word;
  });

  return normalized.join(' ');
}

// ---------------------------------------------------------------------------
// Rule 5: Intensifier removal
// ---------------------------------------------------------------------------

function removeIntensifiers(sentence) {
  const words = sentence.split(/\s+/);
  const filtered = words.filter(word => {
    const clean = word.toLowerCase().replace(/[.,!?;:]+$/, '');
    return !INTENSIFIERS.has(clean);
  });
  return filtered.join(' ');
}

// ---------------------------------------------------------------------------
// Rule 6: Article removal
// ---------------------------------------------------------------------------

function removeArticles(sentence) {
  const words = sentence.split(/\s+/);
  // Don't remove if it would leave fewer than 3 words
  if (words.length <= 3) return sentence;

  const filtered = words.filter(word => {
    const clean = word.toLowerCase().replace(/[.,!?;:]+$/, '');
    return !ARTICLES.has(clean);
  });

  // Safety: if removal leaves < 3 words, keep original
  if (filtered.length < 3) return sentence;
  return filtered.join(' ');
}

// ---------------------------------------------------------------------------
// Rule 7: Connective elimination
// ---------------------------------------------------------------------------

function removeConnectives(sentence) {
  const lower = sentence.toLowerCase();

  for (const connective of CONNECTIVES) {
    // Match connective as whole phrase (case-insensitive)
    const regex = new RegExp(
      '\\b' + connective.replace(/\s+/g, '\\s+') + '\\b,?\\s*',
      'gi'
    );
    sentence = sentence.replace(regex, '');
  }

  // Clean up double spaces and leading/trailing commas
  return sentence.replace(/\s{2,}/g, ' ').replace(/^,\s*/, '').replace(/,\s*$/, '').trim();
}

// ---------------------------------------------------------------------------
// Rule 8: Word limit per sentence
// ---------------------------------------------------------------------------

function limitWords(sentence, maxWords = 5) {
  const words = sentence.split(/\s+/);
  if (words.length <= maxWords) return sentence;

  // Try to split on comma first
  const commaIdx = sentence.indexOf(',');
  if (commaIdx > 0 && commaIdx < sentence.length / 2) {
    const firstPart = sentence.slice(0, commaIdx).trim();
    const firstWords = firstPart.split(/\s+/);
    if (firstWords.length <= maxWords) {
      return firstPart;
    }
  }

  // Truncate to maxWords
  return words.slice(0, maxWords).join(' ');
}

// ---------------------------------------------------------------------------
// Rule 9: Logical completeness check
// ---------------------------------------------------------------------------

function checkCompleteness(sentence) {
  const words = sentence.split(/\s+/).filter(w => w.length > 0);
  // Reject sentences with fewer than 2 meaningful words
  if (words.length < 2) return null;

  // Reject sentences that are just punctuation/numbers
  const meaningfulWords = words.filter(w => /[a-zA-Z]{2,}/.test(w));
  if (meaningfulWords.length === 0) return null;

  return sentence;
}

// ---------------------------------------------------------------------------
// Main compression pipeline
// ---------------------------------------------------------------------------

const RULE_FUNCTIONS = {
  splitSentences,
  resolvePronouns,
  activeVoice,
  presentTense,
  removeIntensifiers,
  removeArticles,
  removeConnectives,
  limitWords,
  checkCompleteness,
};

/**
 * Compress text using Caveman semantic compression.
 *
 * @param {string} text - The text to compress
 * @param {'light'|'semantic'|'aggressive'} [level='semantic'] - Compression level
 * @returns {{ text: string, originalTokens: number, compressedTokens: number, tokenSavings: number, reductionPercent: string, level: string }}
 */
export function compress(text, level = 'semantic') {
  if (!text || text.trim().length === 0) {
    return {
      text: '',
      originalTokens: 0,
      compressedTokens: 0,
      tokenSavings: 0,
      reductionPercent: '0%',
      level,
    };
  }

  const originalTokens = estimateTokens(text);
  const config = COMPRESS_LEVELS[level] || COMPRESS_LEVELS.semantic;
  const rules = config.rules;

  let result = text;

  // Step 1: Split into sentences (always done for semantic/aggressive)
  let sentences = [result];
  if (rules.includes('splitSentences')) {
    sentences = splitSentences(result);
  }

  // Step 2: Apply array-level rules first (resolvePronouns needs full context)
  if (rules.includes('resolvePronouns')) {
    sentences = resolvePronouns(sentences);
  }

  // Step 3: Apply per-sentence rules
  const processed = sentences.map(sentence => {
    let s = sentence;

    for (const ruleName of rules) {
      if (ruleName === 'splitSentences') continue; // Already done
      if (ruleName === 'resolvePronouns') continue; // Already done at array level
      if (ruleName === 'checkCompleteness') continue; // Done at end

      const ruleFn = RULE_FUNCTIONS[ruleName];
      if (ruleFn) {
        s = ruleFn(s);
      }
    }

    // Final completeness check
    if (rules.includes('checkCompleteness')) {
      s = checkCompleteness(s);
    }

    return s;
  }).filter(s => s !== null && s.trim().length > 0);

  // Step 3: Rejoin sentences
  result = processed.join('. ') + (processed.length > 0 ? '.' : '');

  // Clean up: normalize spacing
  result = result
    .replace(/\s{2,}/g, ' ')
    .replace(/\s+\./g, '.')
    .replace(/\.{2,}/g, '.')
    .replace(/,\s*,/g, ',')
    .trim();

  const compressedTokens = estimateTokens(result);
  const tokenSavings = originalTokens - compressedTokens;
  const reductionPercent = originalTokens > 0
    ? Math.round((tokenSavings / originalTokens) * 100)
    : 0;

  return {
    text: result,
    originalTokens,
    compressedTokens,
    tokenSavings,
    reductionPercent: `${reductionPercent}%`,
    level,
  };
}

/**
 * Estimate token count using word-boundary regex.
 * Rough approximation: ~1.3 tokens per word for English text.
 *
 * @param {string} text
 * @returns {number}
 */
export function estimateTokens(text) {
  if (!text) return 0;
  // Count words (split on whitespace and punctuation boundaries)
  const words = text.split(/[\s]+/).filter(w => w.length > 0);
  // Rough estimate: 1.3 tokens per word (GPT tokenizer average)
  return Math.ceil(words.length * 1.3);
}

/**
 * Get available compression levels and their descriptions.
 * @returns {object}
 */
export function getLevels() {
  return Object.entries(COMPRESS_LEVELS).reduce((acc, [key, val]) => {
    acc[key] = { description: val.description, expectedSavings: val.expectedSavings };
    return acc;
  }, {});
}

// ---------------------------------------------------------------------------
// CLI entry point
// ---------------------------------------------------------------------------

function parseArgs() {
  const args = process.argv.slice(2);
  const opts = {
    text: '',
    file: '',
    level: 'semantic',
    format: 'text',
    stats: false,
  };

  for (let i = 0; i < args.length; i++) {
    switch (args[i]) {
      case '--text':
        opts.text = args[++i];
        break;
      case '--file':
        opts.file = args[++i];
        break;
      case '--level':
        opts.level = args[++i];
        if (!COMPRESS_LEVELS[opts.level]) {
          console.error(`Error: Unknown level "${opts.level}". Use: light, semantic, aggressive`);
          process.exit(1);
        }
        break;
      case '--format':
        opts.format = args[++i];
        break;
      case '--stats':
        opts.stats = true;
        break;
      case '--levels':
        console.log(JSON.stringify(getLevels(), null, 2));
        process.exit(0);
      case '--help':
      case '-h':
        printHelp();
        process.exit(0);
    }
  }

  return opts;
}

function printHelp() {
  console.log(`
🦴 Caveman Compression — Strip grammar. Keep facts. Save tokens.

Usage: node caveman.mjs [options]

Options:
  --text <text>       Text to compress
  --file <path>       Read text from file
  --level <level>     Compression level: light, semantic, aggressive (default: semantic)
  --format <fmt>      Output format: text, json (default: text)
  --stats             Show compression statistics
  --levels            List available compression levels
  -h, --help          Show this help

Levels:
  light       Stop-word removal only (15-20% savings)
  semantic    Content selection + lemmatization (25-35% savings)
  aggressive  Maximum compression (35-50% savings)

Examples:
  node caveman.mjs --text "The quick brown fox jumps over the lazy dog" --level aggressive
  node caveman.mjs --file article.txt --level semantic --stats
  node caveman.mjs --text "..." --format json
`);
}

async function main() {
  const opts = parseArgs();

  let text = opts.text;
  if (opts.file) {
    if (!existsSync(opts.file)) {
      console.error(`Error: File not found: ${opts.file}`);
      process.exit(1);
    }
    text = readFileSync(opts.file, 'utf-8');
  }

  if (!text) {
    console.error('Error: Provide --text or --file');
    process.exit(1);
  }

  const result = compress(text, opts.level);

  if (opts.format === 'json') {
    console.log(JSON.stringify({
      compressed: result.text,
      stats: {
        originalTokens: result.originalTokens,
        compressedTokens: result.compressedTokens,
        tokenSavings: result.tokenSavings,
        reductionPercent: result.reductionPercent,
        level: result.level,
      },
    }, null, 2));
  } else {
    console.log(result.text);
    if (opts.stats) {
      console.log('\n--- Compression Stats ---');
      console.log(`Level: ${result.level}`);
      console.log(`Original: ~${result.originalTokens} tokens`);
      console.log(`Compressed: ~${result.compressedTokens} tokens`);
      console.log(`Saved: ${result.tokenSavings} tokens (${result.reductionPercent})`);
    }
  }
}

// Run CLI if executed directly
const IS_CLI = process.argv[1] && (
  process.argv[1].endsWith('/caveman.mjs') || process.argv[1].endsWith('/caveman')
);
if (IS_CLI) {
  main().catch(err => {
    console.error('Error:', err.message);
    process.exit(1);
  });
}

export default { compress, estimateTokens, getLevels, COMPRESS_LEVELS };